Repository morph1904/TygerCaddy, pull requests merged in 2018-05, with the labels that each got.

#4 Dev
  TygerCaddy/hosts/caddyfile.py
  TygerCaddy/templates/base/base.html
  uwsgi.ini
Labels: bug

#71 Readme Updates
  README.md
  docker/Dockerfile
  docker/Dockerfile.alpine
  docker/Dockerfile.ubuntu
Labels: enhancement

#92 Release Alpha-0.1a
  KNOWN ISSUES
  README.md
  TygerCaddy/hosts/caddyfile.py
  docker/entrypoint.sh
  tyger-install-ubuntu.sh
  tyger-uninstall-ubuntu.sh
  tyger-update-ubuntu.sh
  uwsgi.service
Labels: Hotfix
